<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_passwordFromHeader</name>
   <tag></tag>
   <elementGuidId>9de2757a-8567-4496-b7e9-db0fdbd9d2c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='passwordFromHeader']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;passwordFromHeader&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;passwordFromHeader&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3dd24d74-0ff6-4eb7-bc8a-e8e86d4b25d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>51856571-43ca-40f2-97c1-c1c7cad6e798</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>passwordFromHeader</value>
      <webElementGuid>9248a65a-bc13-4a06-856d-1052eed824ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>cb8b90e7-73a2-4e6b-973f-f08f5a38e720</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>general</value>
      <webElementGuid>6d6e74d6-6ab4-4314-8ac9-15bdf85f6dd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;ng-scope&quot;]/table[7]/tbody[1]/tr[1]/td[@class=&quot;content&quot;]/form[@class=&quot;ng-pristine ng-valid&quot;]/table[2]/tbody[1]/tr[2]/td[2]/input[@class=&quot;general&quot;]</value>
      <webElementGuid>7c2f7cf5-22dc-4e76-9037-814f5183a6a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='passwordFromHeader']</value>
      <webElementGuid>91cd12f5-99ca-4018-b906-9eaec450881f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input[2]</value>
      <webElementGuid>7b0b36f1-8b84-4648-9011-1dc892397fcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'passwordFromHeader']</value>
      <webElementGuid>78e56784-a301-40e1-b55c-f386f53df75e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
