<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_submitLogin</name>
   <tag></tag>
   <elementGuidId>3a8fd765-51d1-4e97-a91a-4b394b19c290</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='submitLogin']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;submitLogin&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;log in&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f3b5fcdb-54d1-474c-956f-23f42f089163</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>420dbf6a-2f95-40eb-ba44-61aad9ec4e9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9866c6ce-1c56-4dac-87df-e6128b7ad51a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>submitLogin</value>
      <webElementGuid>76533412-c9bb-4d7f-a3be-3cc6e30938d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>log in</value>
      <webElementGuid>2ce3c26e-5052-45d8-964e-1d734138e443</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;ng-scope&quot;]/table[7]/tbody[1]/tr[1]/td[@class=&quot;content&quot;]/form[@class=&quot;ng-pristine ng-valid&quot;]/table[2]/tbody[1]/tr[2]/td[3]/input[@class=&quot;button&quot;]</value>
      <webElementGuid>8a716217-ee59-42d7-97ec-7643c80a6d64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='submitLogin']</value>
      <webElementGuid>7bb99053-cf22-4e8c-acc7-88c539c68ca7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/input</value>
      <webElementGuid>937d0670-f19f-483c-8871-0e75627ddf73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'submitLogin']</value>
      <webElementGuid>7b1a91a8-d364-43ac-a155-ec22b181fe7c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
