<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Logout</name>
   <tag></tag>
   <elementGuidId>19c32f53-fec6-4b74-97b4-669194959851</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[@onclick='return processViewSDO(this);'])[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(54) > td > a.menuprimary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Logout&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c4e42ad0-fa66-4e6d-ad46-d9e142a8f318</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/APPRWEB/PR/Logout.do</value>
      <webElementGuid>ddc06c97-e10a-4f5f-ab7d-55a2ea472844</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menuprimary</value>
      <webElementGuid>5597cbdd-1b0f-423f-98e3-d07b9757d27d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return processViewSDO(this);</value>
      <webElementGuid>6d047032-799e-4739-b8be-4f9f19ad2fe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>This link takes you to the  Logout section</value>
      <webElementGuid>c297ffeb-f45d-48af-96dc-d85cb8592d89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
											Logout </value>
      <webElementGuid>983c21b5-ac57-429a-bcb4-a42c2877b178</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;ng-scope&quot;]/table[8]/tbody[1]/tr[1]/td[@class=&quot;blue&quot;]/table[1]/tbody[1]/tr[54]/td[1]/a[@class=&quot;menuprimary&quot;]</value>
      <webElementGuid>80544040-639b-4099-8b57-472dd7b86a45</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@onclick='return processViewSDO(this);'])[5]</value>
      <webElementGuid>acc85408-acd1-4e47-909c-3037b1ee17ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Logout')]</value>
      <webElementGuid>fe182a22-a322-4a5a-a288-8bd32c2e9e99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Migrate and Delete Sponsor/Employer'])[1]/following::a[1]</value>
      <webElementGuid>d9f7db18-be71-445a-8db9-af9a01a21fe5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Migrate and Delete Client'])[1]/following::a[2]</value>
      <webElementGuid>0cf68e09-3fea-44e2-94f7-927bb90368d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Work Queues'])[3]/preceding::a[2]</value>
      <webElementGuid>37d54c59-c214-4edf-880f-954050e3240e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Queue:'])[1]/preceding::a[2]</value>
      <webElementGuid>36a36fa8-4245-4ad6-b51a-a5c2872b5390</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Logout']/parent::*</value>
      <webElementGuid>b45c750b-9351-4446-84b5-7d1de527f50f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/APPRWEB/PR/Logout.do')]</value>
      <webElementGuid>bc27ce8f-f61a-4f2e-ac53-8dfedd1c190a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[54]/td/a</value>
      <webElementGuid>d0794497-8e38-47a1-a2e2-3d1a7eb5174b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/APPRWEB/PR/Logout.do' and @title = 'This link takes you to the  Logout section' and (text() = '
											Logout ' or . = '
											Logout ')]</value>
      <webElementGuid>1d4fbb09-e0a3-4f4a-b096-d7e8e1841bcb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
